### ISSUE TITLE
Roadmap to publication in IDR

### ISSUE THREAD

**Issue by will-moore** [IDR/idr0125-way-cellpainting#1]
This issue lists the various tasks to be completed in order to import and curate the idr0125 data into IDR.
The data will be imported in OME-NGFF HCS format.

 - [x] Handle import of large numbers of files in an NGFF plate: https://github.com/ome/ZarrReader/issues/40 
 - [ ] Then, update production IDR with Bio-Formats containing the ZarrReader updates and any other OMERO changes needed
 - [x] Mount s3 data as a file-system using e.g. https://github.com/kahing/goofys to allow OMERO to read the data
 - [ ] Import the data into IDR by importing METADATA.ome.xml for each NGFF fileset, then using mkngff to update the Fileset to the mounted s3 data
 - [ ] Curate the metadata and annotate the imported data
